#ifndef __MrcMcRegisterStructTgl15xxx_h__
#define __MrcMcRegisterStructTgl15xxx_h__
/** @file
  This file was automatically generated. Modify at your own risk.
  Note that no error checking is done in these functions so ensure that the correct values are passed.

@copyright
  Copyright (c) 2010 - 2019 Intel Corporation. All rights reserved
  This software and associated documentation (if any) is furnished
  under a license and may only be used or copied in accordance
  with the terms of the license. Except as permitted by the
  license, no part of this software or documentation may be
  reproduced, stored in a retrieval system, or transmitted in any
  form or by any means without the express written consent of
  Intel Corporation.
  This file contains an 'Intel Peripheral Driver' and is uniquely
  identified as "Intel Reference Module" and is licensed for Intel
  CPUs and chipsets under the terms of your license agreement with
  Intel or your vendor. This file may be modified by the user, subject
  to additional terms of the license agreement.

@par Specification Reference:
**/

#pragma pack(push, 1)

typedef MC0_MAD_INTER_CHANNEL_STRUCT MC1_MAD_INTER_CHANNEL_STRUCT;

typedef MC0_MAD_INTRA_CH0_STRUCT MC1_MAD_INTRA_CH0_STRUCT;

typedef MC0_MAD_INTRA_CH0_STRUCT MC1_MAD_INTRA_CH1_STRUCT;

typedef MC0_MAD_DIMM_CH0_STRUCT MC1_MAD_DIMM_CH0_STRUCT;

typedef MC0_MAD_DIMM_CH0_STRUCT MC1_MAD_DIMM_CH1_STRUCT;

typedef MC0_MCDECS_MISC_STRUCT MC1_MCDECS_MISC_STRUCT;

typedef MC0_MCDECS_CBIT_STRUCT MC1_MCDECS_CBIT_STRUCT;

typedef MC0_CHANNEL_HASH_STRUCT MC1_CHANNEL_HASH_STRUCT;

typedef MC0_CHANNEL_EHASH_STRUCT MC1_CHANNEL_EHASH_STRUCT;

typedef MC0_MC_INIT_STATE_G_STRUCT MC1_MC_INIT_STATE_G_STRUCT;

typedef MC0_MRC_REVISION_STRUCT MC1_MRC_REVISION_STRUCT;

typedef MC0_PWM_PROGRAMMABLE_REQCOUNT_CONFIG_STRUCT MC1_PWM_PROGRAMMABLE_REQCOUNT_CONFIG_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_TOTAL_REQCOUNT_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_PROGRAMMABLE_REQCOUNT_0_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_PROGRAMMABLE_REQCOUNT_1_A0_STRUCT;
typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_PROGRAMMABLE_REQCOUNT_1_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_RDCAS_COUNT_STRUCT;

typedef MC0_PM_SREF_CONFIG_STRUCT MC1_PM_SREF_CONFIG_STRUCT;

typedef MC0_ATMC_STS_STRUCT MC1_ATMC_STS_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_READ_OCCUPANCY_COUNT_STRUCT;

typedef MC0_STALL_DRAIN_STRUCT MC1_STALL_DRAIN_STRUCT;

typedef MC0_IPC_MC_ARB_STRUCT MC1_IPC_MC_ARB_STRUCT;

typedef MC0_IPC_MC_ARB_STRUCT MC1_IPC_MC_DEC_ARB_STRUCT;

typedef MC0_QUEUE_CREDIT_C_STRUCT MC1_QUEUE_CREDIT_C_STRUCT;

typedef MC0_ECC_INJ_ADDR_COMPARE_STRUCT MC1_ECC_INJ_ADDR_COMPARE_STRUCT;

typedef MC0_REMAPBASE_STRUCT MC1_REMAPBASE_STRUCT;

typedef MC0_REMAPLIMIT_STRUCT MC1_REMAPLIMIT_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_WRCAS_COUNT_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_COMMAND_COUNT_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_NON_SR_COUNT_STRUCT;

typedef MC0_TOLUD_STRUCT MC1_TOLUD_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_GLB_DRV_OFF_COUNT_STRUCT;

typedef MC0_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT MC1_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT;

typedef MC0_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT MC1_GDXC_DDR_SYS_ADD_FILTER_MASK_1_STRUCT;

typedef MC0_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT MC1_GDXC_DDR_SYS_ADD_FILTER_MATCH_0_STRUCT;

typedef MC0_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT MC1_GDXC_DDR_SYS_ADD_FILTER_MATCH_1_STRUCT;

typedef MC0_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT MC1_GDXC_DDR_SYS_ADD_TRIGGER_MASK_STRUCT;

typedef MC0_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT MC1_GDXC_DDR_SYS_ADD_TRIGGER_MATCH_STRUCT;

typedef MC0_SC_QOS_STRUCT MC1_SC_QOS_STRUCT;

typedef MC0_CH0_CR_MCSCHEDS_GLOBAL_DRIVER_GATE_CFG_STRUCT MC1_MCMAINS_GLOBAL_DRIVER_GATE_CFG_STRUCT;

typedef MC0_CH0_CR_PM_ALL_RANKS_CKE_LOW_COUNT_STRUCT MC1_PWM_COUNTERS_DURATION_STRUCT;

typedef MC0_CH0_CR_PM_ALL_RANKS_CKE_LOW_COUNT_STRUCT MC1_PWM_COUNTERS_DURATION_A0_STRUCT;
typedef MC0_MCDECS_SECOND_CBIT_STRUCT MC1_MCDECS_SECOND_CBIT_STRUCT;

typedef MC0_ECC_INJ_ADDR_MASK_STRUCT MC1_ECC_INJ_ADDR_MASK_STRUCT;

typedef MC0_SC_QOS2_STRUCT MC1_SC_QOS2_STRUCT;

typedef MC0_SC_QOS3_STRUCT MC1_SC_QOS3_STRUCT;

typedef MC0_NORMALMODE_CFG_STRUCT MC1_NORMALMODE_CFG_STRUCT;

typedef MC0_MC_CPGC_CMI_STRUCT MC1_MC_CPGC_CMI_STRUCT;

typedef MC0_MC_CPGC_MISC_DFT_STRUCT MC1_MC_CPGC_MISC_DFT_STRUCT;

typedef MC0_PARITYERRLOG_STRUCT MC1_PARITYERRLOG_STRUCT;

typedef MC0_PARITY_ERR_INJ_STRUCT MC1_PARITY_ERR_INJ_STRUCT;

typedef MC0_PARITY_CONTROL_STRUCT MC1_PARITY_CONTROL_STRUCT;

typedef MC0_DDRPL_CFG_DTF_STRUCT MC1_DDRPL_CFG_DTF_STRUCT;

typedef MC0_DDRPL_FILTER_DTF_STRUCT MC1_DDRPL_FILTER_DTF_STRUCT;

typedef MC0_DDRPL_DEBUG_DTF_STRUCT MC1_DDRPL_DEBUG_DTF_STRUCT;

typedef MC0_DDRPL_VISA_LANES_STRUCT MC1_DDRPL_VISA_LANES_STRUCT;

typedef MC0_DDRPL_VISA_CFG_DTF_STRUCT MC1_DDRPL_VISA_CFG_DTF_STRUCT;

#pragma pack(pop)
#endif
