## @file Makefile
#
# Windows makefile for 'BfmLib' module build.
#
# Copyright (c) 2007 - 2014, Intel Corporation. All rights reserved.<BR>
#
# This program and the accompanying materials
# are licensed and made available under the terms and conditions of the BSD License
# which accompanies this distribution.  The full text of the license may be found at
# http://opensource.org/licenses/bsd-license.php
#
# THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
# WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
#
##

!INCLUDE $(EDK_TOOLS_PATH)\Source\C\Makefiles\ms.common

APPNAME = BfmLib

LIBS = $(LIB_PATH)\Common.lib

OBJECTS = BinFileManager.obj BfmLib.obj

!INCLUDE $(EDK_TOOLS_PATH)\Source\C\Makefiles\ms.app

